#!/bin/sh

mkdir -p $GEN

cat << EOF > $AUTO_H
#ifndef AUTO_H
#define AUTO_H


#define WSGI_COMPILER "`$CC -v 2>&1 | grep ' version '`"

EOF

if [ $DEBUG ]; then
    define DEBUG
fi

case $SYSTEM in

    Darwin)
        define HAVE_KQUEUE
        incs="$incs -I /opt/local/include"
        libs="$libs -L /opt/local/lib"
        modules="$modules kqueue"
    ;;

    FreeBSD)
        define HAVE_KQUEUE
        incs="$incs -I /usr/local/include"
        libs="$libs -L /usr/local/lib"
        modules="$modules kqueue"
    ;;

    Linux)
        define HAVE_EPOLL
        modules="$modules epoll"
    ;;

esac

cat << EOF >> $AUTO_H

#endif /* AUTO_H */
EOF

cat << EOF > $MODULES_H
#ifndef MODULES_H
#define MODULES_H


#include <wsgi_core.h>

EOF

for m in $modules ; do
    echo "extern wsgi_module_t ${m}_module;" >> $MODULES_H
done

cat << EOF >> $MODULES_H

wsgi_module_t* modules[] = {
EOF

for m in $modules ; do
    echo "    &${m}_module," >> $MODULES_H
done

cat << EOF >> $MODULES_H
};

#endif /* MODULES_H */
EOF
